name: travelwithmurage
favicon: null
layout_spectrum: 0.7142432099208236
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9095382546074688
  lightness: 0.021620343904942274
  saturation: 0.8144500216003507
  rhythmicContrast: 0.32067254558205605
purpose: []
